// <auto-generated />
using System;
using GymApp.Data.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524153811_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymApp.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GymApp.Entities.BodyPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BodyParts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chest"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Back"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Legs"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shoulders"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Arms"
                        });
                });

            modelBuilder.Entity("GymApp.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BodyPartId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BodyPartId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyPartId = 1,
                            Description = "Barbell chest press on a flat bench.",
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = 2,
                            BodyPartId = 1,
                            Description = "Dumbbell press on an incline bench.",
                            Name = "Incline Dumbbell Press"
                        },
                        new
                        {
                            Id = 3,
                            BodyPartId = 1,
                            Description = "Bodyweight push-ups on the floor.",
                            Name = "Push-Ups"
                        },
                        new
                        {
                            Id = 4,
                            BodyPartId = 1,
                            Description = "High-to-low chest fly using cables.",
                            Name = "Cable Crossover"
                        },
                        new
                        {
                            Id = 5,
                            BodyPartId = 1,
                            Description = "Flat bench chest flyes with dumbbells.",
                            Name = "Dumbbell Flyes"
                        },
                        new
                        {
                            Id = 6,
                            BodyPartId = 1,
                            Description = "Barbell press on a decline bench.",
                            Name = "Decline Barbell Press"
                        },
                        new
                        {
                            Id = 7,
                            BodyPartId = 1,
                            Description = "Seated chest press using a machine.",
                            Name = "Machine Chest Press"
                        },
                        new
                        {
                            Id = 8,
                            BodyPartId = 1,
                            Description = "Seated chest fly using the pec deck machine.",
                            Name = "Pec Deck Fly"
                        },
                        new
                        {
                            Id = 9,
                            BodyPartId = 1,
                            Description = "Bodyweight dips leaning forward to target chest.",
                            Name = "Chest Dips"
                        },
                        new
                        {
                            Id = 10,
                            BodyPartId = 1,
                            Description = "Lying dumbbell pullover for lower chest.",
                            Name = "Dumbbell Pullover"
                        },
                        new
                        {
                            Id = 11,
                            BodyPartId = 2,
                            Description = "Overhand grip bodyweight pull-ups.",
                            Name = "Pull-Up"
                        },
                        new
                        {
                            Id = 12,
                            BodyPartId = 2,
                            Description = "Bent-over barbell row.",
                            Name = "Barbell Row"
                        },
                        new
                        {
                            Id = 13,
                            BodyPartId = 2,
                            Description = "Wide-grip cable pulldown.",
                            Name = "Lat Pulldown"
                        },
                        new
                        {
                            Id = 14,
                            BodyPartId = 2,
                            Description = "Conventional barbell deadlift.",
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = 15,
                            BodyPartId = 2,
                            Description = "Close-grip seated row with cables.",
                            Name = "Seated Cable Row"
                        },
                        new
                        {
                            Id = 16,
                            BodyPartId = 2,
                            Description = "Heavy T-Bar rowing machine or landmine.",
                            Name = "T-Bar Row"
                        },
                        new
                        {
                            Id = 17,
                            BodyPartId = 2,
                            Description = "Bent-over row using one arm supported by a bench.",
                            Name = "Single-Arm Dumbbell Row"
                        },
                        new
                        {
                            Id = 18,
                            BodyPartId = 2,
                            Description = "Cable pulldown keeping arms straight to isolate lats.",
                            Name = "Straight-Arm Pulldown"
                        },
                        new
                        {
                            Id = 19,
                            BodyPartId = 2,
                            Description = "Rope face pulls targeting upper back.",
                            Name = "Face Pulls"
                        },
                        new
                        {
                            Id = 20,
                            BodyPartId = 2,
                            Description = "Hyperextensions for the lower back.",
                            Name = "Back Extension"
                        },
                        new
                        {
                            Id = 21,
                            BodyPartId = 3,
                            Description = "Traditional barbell back squat.",
                            Name = "Squat"
                        },
                        new
                        {
                            Id = 22,
                            BodyPartId = 3,
                            Description = "Seated machine leg extension.",
                            Name = "Leg Extension"
                        },
                        new
                        {
                            Id = 23,
                            BodyPartId = 3,
                            Description = "Machine seated leg press.",
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = 24,
                            BodyPartId = 3,
                            Description = "Straight-leg barbell RDL for hamstrings.",
                            Name = "Romanian Deadlift"
                        },
                        new
                        {
                            Id = 25,
                            BodyPartId = 3,
                            Description = "Machine lying leg curl for hamstrings.",
                            Name = "Lying Leg Curl"
                        },
                        new
                        {
                            Id = 26,
                            BodyPartId = 3,
                            Description = "Dumbbell walking lunges.",
                            Name = "Walking Lunges"
                        },
                        new
                        {
                            Id = 27,
                            BodyPartId = 3,
                            Description = "Standing barbell or machine calf raises.",
                            Name = "Calf Raises"
                        },
                        new
                        {
                            Id = 28,
                            BodyPartId = 3,
                            Description = "Single-leg squat with rear foot elevated.",
                            Name = "Bulgarian Split Squat"
                        },
                        new
                        {
                            Id = 29,
                            BodyPartId = 3,
                            Description = "Machine hack squat.",
                            Name = "Hack Squat"
                        },
                        new
                        {
                            Id = 30,
                            BodyPartId = 3,
                            Description = "Barbell hip thrusts/glute bridges.",
                            Name = "Glute Bridge"
                        },
                        new
                        {
                            Id = 31,
                            BodyPartId = 4,
                            Description = "Standing strict barbell military press.",
                            Name = "Overhead Press"
                        },
                        new
                        {
                            Id = 32,
                            BodyPartId = 4,
                            Description = "Standing dumbbell lateral raises.",
                            Name = "Lateral Raise"
                        },
                        new
                        {
                            Id = 33,
                            BodyPartId = 4,
                            Description = "Dumbbell front raises for anterior delts.",
                            Name = "Front Raise"
                        },
                        new
                        {
                            Id = 34,
                            BodyPartId = 4,
                            Description = "Seated rotating dumbbell press.",
                            Name = "Arnold Press"
                        },
                        new
                        {
                            Id = 35,
                            BodyPartId = 4,
                            Description = "Machine flyes for rear deltoids.",
                            Name = "Reverse Pec Deck"
                        },
                        new
                        {
                            Id = 36,
                            BodyPartId = 4,
                            Description = "Barbell upright row.",
                            Name = "Upright Row"
                        },
                        new
                        {
                            Id = 37,
                            BodyPartId = 4,
                            Description = "Single-arm lateral raise using a low cable.",
                            Name = "Cable Lateral Raise"
                        },
                        new
                        {
                            Id = 38,
                            BodyPartId = 4,
                            Description = "Overhead press with slight leg drive.",
                            Name = "Push Press"
                        },
                        new
                        {
                            Id = 39,
                            BodyPartId = 4,
                            Description = "Seated machine overhead press.",
                            Name = "Machine Shoulder Press"
                        },
                        new
                        {
                            Id = 40,
                            BodyPartId = 4,
                            Description = "Heavy dumbbell shrugs for traps.",
                            Name = "Dumbbell Shrugs"
                        },
                        new
                        {
                            Id = 41,
                            BodyPartId = 5,
                            Description = "Standing straight barbell bicep curl.",
                            Name = "Barbell Bicep Curl"
                        },
                        new
                        {
                            Id = 42,
                            BodyPartId = 5,
                            Description = "Cable rope pushdown for triceps.",
                            Name = "Triceps Pushdown"
                        },
                        new
                        {
                            Id = 43,
                            BodyPartId = 5,
                            Description = "Dumbbell curl with neutral grip.",
                            Name = "Hammer Curl"
                        },
                        new
                        {
                            Id = 44,
                            BodyPartId = 5,
                            Description = "Dumbbell or cable overhead extension.",
                            Name = "Overhead Triceps Extension"
                        },
                        new
                        {
                            Id = 45,
                            BodyPartId = 5,
                            Description = "EZ-Bar bicep curl on a preacher bench.",
                            Name = "Preacher Curl"
                        },
                        new
                        {
                            Id = 46,
                            BodyPartId = 5,
                            Description = "Lying EZ-Bar triceps extensions.",
                            Name = "Skull Crushers"
                        },
                        new
                        {
                            Id = 47,
                            BodyPartId = 5,
                            Description = "Seated single-arm dumbbell bicep curl.",
                            Name = "Concentration Curl"
                        },
                        new
                        {
                            Id = 48,
                            BodyPartId = 5,
                            Description = "Triceps dips using a flat bench.",
                            Name = "Bench Dips"
                        },
                        new
                        {
                            Id = 49,
                            BodyPartId = 5,
                            Description = "Standing straight-bar cable curl.",
                            Name = "Cable Bicep Curl"
                        },
                        new
                        {
                            Id = 50,
                            BodyPartId = 5,
                            Description = "Barbell bench press with a narrow grip for triceps.",
                            Name = "Close-Grip Bench Press"
                        });
                });

            modelBuilder.Entity("GymApp.Entities.ExerciseLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.Property<string>("WeightUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("ExercisesLog");
                });

            modelBuilder.Entity("GymApp.Entities.WorkoutPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutPlans");
                });

            modelBuilder.Entity("GymApp.Entities.WorkoutPlanExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("WorkoutPlanExercises");
                });

            modelBuilder.Entity("GymApp.Entities.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkoutPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("GymApp.Entities.Exercise", b =>
                {
                    b.HasOne("GymApp.Entities.BodyPart", "BodyPart")
                        .WithMany("Exercises")
                        .HasForeignKey("BodyPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyPart");
                });

            modelBuilder.Entity("GymApp.Entities.ExerciseLog", b =>
                {
                    b.HasOne("GymApp.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymApp.Entities.WorkoutSession", "WorkoutSession")
                        .WithMany("ExerciseLogs")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("GymApp.Entities.WorkoutPlan", b =>
                {
                    b.HasOne("GymApp.Entities.AppUser", "User")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymApp.Entities.WorkoutPlanExercise", b =>
                {
                    b.HasOne("GymApp.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymApp.Entities.WorkoutPlan", "WorkoutPlan")
                        .WithMany("WorkoutPlanExercise")
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("GymApp.Entities.WorkoutSession", b =>
                {
                    b.HasOne("GymApp.Entities.AppUser", "User")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymApp.Entities.WorkoutPlan", "WorkoutPlan")
                        .WithMany()
                        .HasForeignKey("WorkoutPlanId");

                    b.Navigation("User");

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("GymApp.Entities.AppUser", b =>
                {
                    b.Navigation("WorkoutPlans");

                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("GymApp.Entities.BodyPart", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("GymApp.Entities.WorkoutPlan", b =>
                {
                    b.Navigation("WorkoutPlanExercise");
                });

            modelBuilder.Entity("GymApp.Entities.WorkoutSession", b =>
                {
                    b.Navigation("ExerciseLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
